#!/bin/csh

#INPUTS:
#dwmri.nii.gz (main image)
#dwmri.bval (units of s/mm2)
#dwmri.bvec (normalized unit vectors in the FSL format)
#t1.nii.gz (used for Synb0-DISCO, Optional)
#rpe.nii.gz (used for RPE correction, Optional)
#rpe.bval (units of s/mm2)
#rpe.bvec (normalized unit vectors in the FSL format)

#run_dtiQA.py: the following arguments are required: 
#in_dir out_dir pe_dir readout_time b0_threshold project
#subject session scans

#6140 no good, bad MRI 

foreach SUBJECT (6156a 6023a 3036a  6001a  6020a  6037a  6059a  6084a  6110a  6129a  6144a  6168a  6196a) 


echo starting dtiQA 4 $SUBJECT



mkdir /scratch/begnocjp/caare_dtiQA7-HARDI_ONLY_EDDY/OUTPUTS/$SUBJECT

cp /home/begnocjp/TBSS_scripts/dtiQA_config.csv /data/h_taylor/Imaging/CAARE_TBSS/caare_dtiQA7-HARDI_ONLY_orig/INPUTS/$SUBJECT
 
singularity run -e \
-B /data/h_taylor/Imaging/CAARE_TBSS/caare_dtiQA7-HARDI_ONLY_orig/INPUTS/$SUBJECT/:/INPUTS \
-B /scratch/begnocjp/caare_dtiQA7-HARDI_ONLY_EDDY/OUTPUTS/$SUBJECT/:/OUTPUTS \
-B /data/h_taylor/Imaging/freesurfer_license.txt:/APPS/freesurfer/license.txt \
/scratch/begnocjp/singularities/dtiQA_v7.1.3.simg j --denoise off \
--synb0 off \
--keep_intermediates \
--split_outputs \

echo dtiaQA 4 $SUBJECT complete


end










